---
  - name: "Print debug message"
    debug:
      msg: "file_path: '{{ file_path }}', symlink_target: '{{ symlink_target }}'"

  - name: Check if '{{ file_path }}' already exists
    stat:
      path: "{{ file_path }}"
    register: file_stat

  - name: Check if '{{ file_path }}_BACKUP' already exists
    stat:
      path: "{{ file_path }}_BACKUP"
    register: file_backup_stat

  - name: Fail if both '{{ file_path }}' and '{{ file_path }}_BACKUP' exists
    fail:
      msg: "{{ file_path }} and {{ file_path }}_BACKUP already exists. Stopping execution to prevent removing unwanted files."
    when: (file_stat.stat.exists) and (file_backup_stat.stat.exists)

  - name: If '{{ file_path }}' exists, rename it to '{{ file_path }}_BACKUP'
    command: mv '{{ file_path }}' '{{ file_path }}_BACKUP'
    when: file_stat.stat.exists

  - name: Create symbolic link {{ file_path }} -> {{ symlink_target }}
    file:
      src: "{{ symlink_target }}"
      dest: "{{ file_path }}"
      state: link

  # - name: Check that the exists
  #   stat:
  #     path: "{{ dotfiles_folder_relative_prefix }}"
  #   register: stat

  # - name: Create the file, if it doesnt exist already
  #   file:
  #     path: /etc/file.txt
  #     state: touch
  #   when: not stat_result.stat.exists

    # - name: "Print debug message"
    # debug:
    #   msg: "file_stat.stat.exists: {{ file_stat.stat.exists }}"