---
  - name: Check if '{{ zshrc_path }}' already exists
    stat:
      path: "{{ zshrc_path }}"
    register: zshrc_stat

  - name: Check if '{{ zshrc_path }}_BACKUP' already exists
    stat:
      path: "{{ zshrc_path }}_BACKUP"
    register: zshrc_backup_stat

  - name: Fail if both '{{ zshrc_path }}' and '{{ zshrc_path }}_BACKUP' exists
    fail:
      msg: "{{ zshrc_path }} and {{ zshrc_path }}_BACKUP already exists. Stopping execution to prevent removing unwanted files."
    when: (zshrc_stat.stat.exists) and (zshrc_backup_stat.stat.exists)

  - name: If '{{ zshrc_path }}' exists, rename it to '{{ zshrc_path }}_BACKUP'
    command: mv {{ zshrc_path }} {{ zshrc_path }}_BACKUP
    when: zshrc_stat.stat.exists

  - name: Create symbolic link {{ zshrc_path }} -> {{ dotfiles_folder_relative_prefix }}/zsh/.zshrc
    file:
      src: "{{ dotfiles_folder_relative_prefix }}/zsh/.zshrc"
      dest: "{{ zshrc_path }}"
      state: link

  # - name: Check that the exists
  #   stat:
  #     path: "{{ dotfiles_folder_relative_prefix }}"
  #   register: stat

  # - name: Create the file, if it doesnt exist already
  #   file:
  #     path: /etc/file.txt
  #     state: touch
  #   when: not stat_result.stat.exists

    # - name: "Print debug message"
    # debug:
    #   msg: "zshrc_stat.stat.exists: {{ zshrc_stat.stat.exists }}"