---
  - name: Check if '{{ zprofile_path }}' already exists
    stat:
      path: "{{ zprofile_path }}"
    register: zshrc_stat

  - name: Check if '{{ zprofile_path }}_BACKUP' already exists
    stat:
      path: "{{ zprofile_path }}_BACKUP"
    register: zshrc_backup_stat

  - name: Fail if both '{{ zprofile_path }}' and '{{ zprofile_path }}_BACKUP' exists
    fail:
      msg: "{{ zprofile_path }} and {{ zprofile_path }}_BACKUP already exists. Stopping execution to prevent removing unwanted files."
    when: (zshrc_stat.stat.exists) and (zshrc_backup_stat.stat.exists)

  - name: If '{{ zprofile_path }}' exists, rename it to '{{ zprofile_path }}_BACKUP'
    command: mv {{ zprofile_path }} {{ zprofile_path }}_BACKUP
    when: zshrc_stat.stat.exists

  - name: Create symbolic link {{ zprofile_path }} -> {{ dotfiles_folder_relative_prefix }}/zsh/.zprofile
    file:
      src: "{{ dotfiles_folder_relative_prefix }}/zsh/.zprofile"
      dest: "{{ zprofile_path }}"
      state: link

  # - name: Check that the exists
  #   stat:
  #     path: "{{ dotfiles_folder_relative_prefix }}"
  #   register: stat

  # - name: Create the file, if it doesnt exist already
  #   file:
  #     path: /etc/file.txt
  #     state: touch
  #   when: not stat_result.stat.exists

    # - name: "Print debug message"
    # debug:
    #   msg: "zshrc_stat.stat.exists: {{ zshrc_stat.stat.exists }}"